function plan = buildfile
import matlab.buildtool.tasks.*

plan = buildplan(localfunctions);

plan("clean") = CleanTask;

plan("check") = CodeIssuesTask(...
    Results="analysis-results/codeIssues.sarif",...
    WarningThreshold=38);

plan("test") = TestTask(...
    SourceFiles="source", ...
    TestResults=["test-results/results.xml" "test-results/test-report.html"], ...
    LoggingLevel="detailed") ...
    .addCodeCoverage(...
        ["test-results/coverage.xml", "test-results/coverage-report/index.html"], ...
        MetricLevel="mcdc");

plan.DefaultTasks = ["check" "test"];
end
